### ISSUE TITLE
Test failures with git config color.ui set

### ISSUE THREAD

**Issue by Grinnz** [yanick/git-cpan-patch#29]
Similar issue to https://rt.cpan.org/Ticket/Display.html?id=111645. See attached test failures if color.ui is set to 'always'. Installation works with color.ui set to 'never'.
[git-cpan-patch-test-fail.txt](https://github.com/yanick/git-cpan-patch/files/113219/git-cpan-patch-test-fail.txt)

**Comment by yanick** [comment]
Fixed, thanks!
