### ISSUE TITLE
Respect GIT_* environment variables if they are already set.

### ISSUE THREAD

**Issue by briandfoy** [yanick/git-cpan-patch#31]
In [Author comes out as "unknown" for List::Comprehensions ](https://github.com/yanick/git-cpan-patch/issues/30), I had trouble getting the right author for the clone. I then set the GIT_AUTHOR* variables and tried again. It looks like *::Import sets them itself without checking if they already have a value.

**Comment by yanick** [comment]
I added a `--author-email` and `--author-name` options to `git cpan clone`.
