### ISSUE TITLE
Fails with MooseX-Role-Tempdir-0.100

### ISSUE THREAD

**Issue by andk** [yanick/git-cpan-patch#33]
As per subject. Sample fail report:

http://www.cpantesters.org/cpan/report/a942ce4a-31c3-11e6-8c7e-2746ee1f9a26

This is not limited to bleadperl. My smoker has the same issue with 5.24.0 but the results have not yet arrived at cpantesters. In any case, downgrading to IAMB/MooseX-Role-Tempdir-0.03.tar.gz does as a workaround.

Best,

**Comment by ppisar** [comment]
This is a bug <https://rt.cpan.org/Public/Bug/Display.html?id=119368> in MooseX-Role-Tempdir-0.100.

**Comment by yanick** [comment]
Hmm... Since MooseX::Role::Tempdir didn't get updated in the last 6 months, we could probably change its use for a simple use of Path::Tiny's tempdir.
